kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
  labels:
    {{- include "flannel.labels" . | nindent 4 }}
    {{- with (merge .Values.flannel.rbac.clusterRole.labels .Values.flannel.rbac.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.flannel.rbac.clusterRole.annotations .Values.flannel.rbac.annotations .Values.global.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
{{- if .Values.netpol.enabled }}
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - "policy.networking.k8s.io"
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - list
  - watch
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
  labels:
    {{- include "flannel.labels" . | nindent 4 }}
    {{- with (merge .Values.flannel.rbac.clusterRoleBinding.labels .Values.flannel.rbac.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.flannel.rbac.clusterRoleBinding.annotations .Values.flannel.rbac.annotations .Values.global.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: {{ .Release.Namespace }}
