apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flannel.labels" . | nindent 4 }}
    {{- with .Values.flannel.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge .Values.flannel.serviceAccount.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
