FROM arm64v8/busybox:glibc

MAINTAINER Tom Denham <tom@tigera.io>

ENV FLANNEL_ARCH=arm64

COPY dist/flanneld-$FLANNEL_ARCH /opt/bin/flanneld
COPY dist/iptables-$FLANNEL_ARCH /usr/local/bin/iptables
COPY dist/strongswan-arm /usr/local/
COPY dist/mk-docker-opts.sh /opt/bin/

COPY dist/strongswan-$FLANNEL_ARCH /usr/local/strongswan-arm
COPY dist/libatomic.so.1-$FLANNEL_ARCH /lib/libatomic.so.1
COPY dist/libdl.so.2-$FLANNEL_ARCH /lib/libdl.so.2

ENTRYPOINT ["/opt/bin/flanneld"]
