FROM armel/busybox:glibc

MAINTAINER Tom Denham <tom@tigera.io>

COPY dist/flanneld-arm /opt/bin/flanneld
COPY dist/iptables-arm /usr/local/bin/iptables
COPY dist/mk-docker-opts.sh /opt/bin/
COPY dist/libpthread.so.0-arm /lib/libpthread.so.0
CMD ["/opt/bin/flanneld"]
