FROM armel/busybox:glibc

MAINTAINER Tom Denham <tom@tigera.io>

ENV FLANNEL_ARCH=arm

COPY dist/flanneld-$FLANNEL_ARCH /opt/bin/flanneld
COPY dist/iptables-$FLANNEL_ARCH /usr/local/bin/iptables
COPY dist/mk-docker-opts.sh /opt/bin/
COPY dist/libpthread.so.0-$FLANNEL_ARCH /lib/libpthread.so.0
COPY dist/ld64.so.1-$FLANNEL_ARCH /lib/ld64.so.1
COPY dist/libc.so.6-$FLANNEL_ARCH /lib/libc.so.6


ENTRYPOINT ["/opt/bin/flanneld"]
