FROM s390x/busybox:glibc

MAINTAINER Tom Denham <tom@tigera.io>

ENV FLANNEL_ARCH=s390x

COPY dist/flanneld-$FLANNEL_ARCH /opt/bin/flanneld
COPY dist/iptables-$FLANNEL_ARCH /usr/local/bin/iptables
COPY dist/mk-docker-opts.sh /opt/bin/

ENTRYPOINT ["/opt/bin/flanneld"]
