name: build flannel

on: pull_request

env:
  GO_VERSION: "1.25"
  LINUX_ARCHES: "amd64 arm arm64 s390x ppc64le riscv64"
  REPOSITORY: flannel/flannel

permissions:
  contents: read

jobs:
  chart-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - name: Set up Helm
        uses: Azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 #v4
        with:
          version: '3.19.0'

      - name: Run chart tests
        run: make chart-test

  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - name: set tag
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set up Go 1.x
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: go mod vendor
        run: go mod vendor

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 #v4.1.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 #v6.2.0
        with:
          images: ${{ env.REPOSITORY }}
          flavor: latest=false
          tags: |
            type=ref, event=branch

      - name: Build multi-arch Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a #v6.15.0
        with:
          context: .
          file: images/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64,linux/arm,linux/s390x,linux/ppc64le,linux/riscv64
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ env.GIT_TAG }}

      - name: build for windows
        run: make dist/flanneld.exe
