name: kind e2e tests for flannel

on: pull_request

env:
  ARCH: amd64
  GO_VERSION: "1.25"
  KUBECONFIG: ${HOME}/.kube/config

permissions:
  contents: read

jobs:
  kind-e2e-tests:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Set up Go 1.x
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: set up modules
        run: sudo modprobe br_netfilter overlay

      - name: run e2e tests with kind
        run: make kind-e2e-test
